---
- name: deploy RabbitMQ and setup the environment
  hosts:
    - all_group
  #gather_facts: False
  user: centos
  become: yes
  roles:
    - set_hostname
    - install_rabbitmq

- name: Configure RabbitMQ Cluster
  hosts:
    - workers
  user: centos
  become: yes
  roles:
    - cluster_setup
